spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ainews
    username: ainews
    password: ainews
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

gdelt:
  collect-interval-ms: 900000

logging:
  level:
    com.mesgan.ainews: DEBUG
    org.hibernate.SQL: DEBUG
